### ISSUE TITLE
How to do Apple versioning in CMake?

### ISSUE THREAD

**Issue by madebr** [madebr/SDL_image#1]
working branch: https://github.com/madebr/SDL_image/tree/cmake_work

I don't know how to reproduce the Macos dylib versioning using CMake.
Since I also don't own Apple hardware, I'm unable to build it locally.

The goal is to reproduce the versioning of lbiraries generated by the SDL2_image project in the Xcode subfolder.

- The CMake build system defines libtool version variables for versioning the .so libraries on Linux (these match the autotools build).
- For Macos, the following variables are available for dylib versioning `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION`.

- [`SOVERSION`](https://cmake.org/cmake/help/latest/prop_tgt/SOVERSION.html) and [`VERSION`](https://cmake.org/cmake/help/latest/prop_tgt/VERSION.html) contain a section about MACH-O versioning.
- CMake provides [`MACHO_COMPATIBILITY_VERSION`](https://cmake.org/cmake/help/latest/prop_tgt/MACHO_COMPATIBILITY_VERSION.html) and [`MACHO_CURRENT_VERSION`](https://cmake.org/cmake/help/latest/prop_tgt/MACHO_CURRENT_VERSION.html), but these are for CMake 3.17+ (=march 2020, which is perhaps a bit too new for ubuntu 20.04 LTS)
The current minimum cmake required version is 3.14.

@SpaceIm Can you please help me out?

**Comment by SpaceIm** [comment]
I don't know, does it ever work in CMake 3.14+ with another generator than XCode?

**Comment by madebr** [comment]
I didn't test with the XCode generator.
But I think it will work for all generators, even for Xcode, but it just won't set the versioning.

I ended up peeking into SDL2's cmake script and borrowing their approach:
https://github.com/libsdl-org/SDL/blob/e9c7b5191c3ed783489d66ba825f2101810a9b58/CMakeLists.txt#L610-L611

**Comment by SpaceIm** [comment]
> I ended up peeking into SDL2's cmake script and borrowing their approach:
https://github.com/libsdl-org/SDL/blob/e9c7b5191c3ed783489d66ba825f2101810a9b58/CMakeLists.txt#L610-L611

Yes, I think there is no other choice.
